### ISSUE TITLE
"How to use" part is quite vague

### ISSUE THREAD

**Issue by marchingon12** [KunoiSayami/Things-Forward-telegram#5]
- Edit forward target
- Set up PostgreSQL database and tables

I find that these two aren't exactly easy for beginners to set up (like me). For example, you could specify the forward target being in which file to edit, and how to set up PostgreSQL database and tables to make it work. Would it be able to work with ElephantSQL as well?

**Comment by KunoiSayami** [comment]
> Would it be able to work with ElephantSQL as well?

It should be work with PostgreSQL like databases, but seems I haven't update configure file at that time. I'll update configure file later.

-------

> Edit forward target

In configure file section:
```ini
[forward]
; forward only type photo message to channel_id
to_photo =
; forward only type video message to channel_id
to_video =
; same but forward bot message
bot_for =
; same but forward user specify channel
to_anime =
; same but forward type gif
to_gif = 
; same but forward type document and extension name in jpg, png, etc.
to_doc = 
; same but forward low quality image
to_lowq = 
; other file previous not listed
to_other =

; query command specify section
query_photo =
query_video =
qeury_doc = 

; bypass forward channel
bypass_list = []
; user in blacklist will not forward, but maybe forward to "to_blacklist" channel
black_list = []
to_blacklist =

; mapping target, forward message as specify type
special = {}
; definion low quality image, use resolution to judgement
lowq_resolution = 
```

**Comment by KunoiSayami** [comment]
> Set up PostgreSQL database and tables

Import [bot.sql](https://github.com/KunoiSayami/Things-Forward-telegram/blob/master/bot.sql) to your postgresql database.

**Comment by aahnik** [comment]
Hi friends @KunoiSayami, @x0x8x , @jc-v and @marchingon12  , would you please check out my script ?
https://github.com/aahnik/telegram-chat-forward ( built using telethon )

No database required. Sends all messages from a chat to another. Its features are a bit different. **It will run once, finish the job and stop.**

great for backing up content from one chat to another. 

I would love to get your feedback on my code and about features.

thank you

>PS: I also have another script that does live syncing, from source chat to destination chat. ( editing and deleting in source would reflect in destination )

**Comment by KunoiSayami** [comment]
@aahnik Thanks for your recommendation, but this project forward message from multiple channel/group to another one, your script only part of the project has been implemented.

**Comment by aahnik** [comment]
@KunoiSayami my script also supports forwarding from multiple to multiple.

it can support many to many. By configuring in the .ini file.

but there will be some repitition in my fashion. ( A -> B and again A->C ) that i realized now.
I will work on overcoming that.

thanks a lot for your feedback.

**Comment by KunoiSayami** [comment]
@aahnik This project use database to prevert forward message which contain the same media.

Except configure field, this is the only reason I use database.
