### ISSUE TITLE
Poderia Ajudar a leigo a instalar? 

### ISSUE THREAD

**Issue by saviolavc** [KunoiSayami/Things-Forward-telegram#6]
POder descrever bem melhor a instalação? 
Se você não tem api_ide api_hash, obtenha-os no telegrama
Copiar config.ini.defaultparaconfig.ini
Editar alvo avançado
Configurar banco de dados e tabelas PostgreSQL
Corre forward.py
?????

**Comment by KunoiSayami** [comment]
**Please use English to ask question.** For postgresql table structure, you can find it in `bot.sql`.
