### ISSUE TITLE
Anti-Forward

### ISSUE THREAD

**Issue by kobasis12** [KunoiSayami/Things-Forward-telegram#8]
Dude, how to counter this Auto Forward??
Cause it harming my private channel

**Comment by KunoiSayami** [comment]
Please describe your question in detail. Btw, is any non-administrator user can spaming your own channel?

**Comment by kobasis12** [comment]
I have paid private channel, then any member use "tforward android apps",
this forward to non-member. Even my post on that channel is secret for
member only.
The inpostor join my paid private channel, but he sell again with
underprice.

Sab, 10 Jul 2021 pukul 17.13 Kunoi Sayami ***@***.***>
menulis:

**Comment by KunoiSayami** [comment]
You must pay attention to this: this project is just tool, whatever user how to use it. So I will close this issue and mark it as `off-topic`.
Feel free to open new issue if you have more question.
